Create octofet package and add usage examples.
amperka/OctofetPi pull request #2
Opened 2020-03-25 08:16 UTC by AlexErAmp

2020-03-25 09:36 UTC, nkrkv requested changes

2020-03-25 09:36 UTC, nkrkv commented on examples/multiple_octofets.py
> +""" The program turns on all the switches in course, then turns them off."""
```suggestion
"""The program turns on all the channels one by one, then turns all off."""
```

2020-03-25 09:36 UTC, nkrkv commented on examples/multiple_octofets.py
> +    print("Please enter the number of devices used.")
```suggestion
    print("Enter number of Octofets in chain (1 for single one):")
```

2020-03-25 09:36 UTC, nkrkv commented on examples/octofet_control.py
> +Octofet board."""
```suggestion
"""Command line utility that allows you to control the state of switches on an
Octofet board."""
```

2020-03-25 09:36 UTC, nkrkv commented on examples/octofet_control.py
> +            print("Enter the number of the switch you want to turn on/off.")
```suggestion
            print("Enter # of channel to manage (0 to 7):")
```

2020-03-25 09:36 UTC, nkrkv commented on examples/octofet_control.py
> +                print("The selected switch is not on the board, try again!")
```suggestion
                print("Error: Value should be in 0..7 range")
```

2020-03-25 09:36 UTC, nkrkv commented on examples/octofet_control.py
> +            print('Enter "on" to turn on the switch or "off" to turn it off.')
```suggestion
            print('Enter "on" to turn on the switch or "off" to turn it off:')
```

2020-03-25 09:36 UTC, nkrkv commented on examples/octofet_control.py
> +                print("Incorrect command, try again!")
```suggestion
                print("Error: Incorrect command, expected `on` or `off`")
```

2020-03-25 12:08 UTC, nkrkv approved these changes
LGTM :ok_hand:

2020-03-26 15:24 UTC, nomad605dis approved these changes
😍

2020-03-26 15:29 UTC, merged